### ISSUE TITLE
Install yoast with npm and then run it in nodejs

### ISSUE THREAD

**Issue by HappyLDE** [Yoast/javascript#385]
## Explanation
I'm trying to get Yoast to work in a nodejs app, so I installed it following these steps (node v12.13.0):

- In an empty folder I opened the terminal and typed:
`npm install yoastseo`

- Result:
```
npm WARN saveError ENOENT: no such file or directory, open '/home/bringw/www/first-app/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/bringw/www/first-app/package.json'
npm WARN first-app No description
npm WARN first-app No repository field.
npm WARN first-app No README data
npm WARN first-app No license field.

+ yoastseo@1.61.0
added 22 packages from 16 contributors and audited 1713 packages in 3.676s
found 0 vulnerabilities
```

- Next I created an empty file named app.js an pasted the following code (from the homepage):
```
import { AnalysisWebWorker } from "yoastseo";

const worker = new AnalysisWebWorker( self );
worker.register();
```

- Then run the file with node like follows:
`node app.js`

- And the result:
```
/home/bringw/www/first-app/app.js:1
import { AnalysisWebWorker } from "yoastseo";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

## Feedback?
The documentation is lacking seriously, there is no guide or anything, what are we supposed to do? :(

Thank you :D

**Comment by Cool-Programmer** [comment]
Hello, i'm also stuck on this... Do you have any progress?

**Comment by HappyLDE** [comment]
> Hello, i'm also stuck on this... Do you have any progress?

Still no progress since i dont have experience with nodejs

**Comment by rakeshshubhu** [comment]
I'm kind of progressing through it. But unable to generate the report... 
so I'm sort of creating my own report given the data.

**Comment by asokb4u** [comment]
Hello, any update on this. we are waiting since long time. Feel this is very nice package, but struck due to this issue. till version 1.22.4 works in nodejs project. after that it broken.
